version: '3'

services:
  order-board:
    image: python:3.10-slim
    container_name: nas_order_board
    ports:
      - "7899:7899"
    volumes:
      - /vol2/1000/Docker/order_system/backend:/app
      - /vol2/1000/Docker/order_system/data:/app/data
      - /vol2/1000/Docker/order_system/frontend:/app/frontend
    working_dir: /app
    # 🎯 核心新增：强行把容器内部的时区设定为亚洲/上海（即北京时间东八区）
    environment:
      - TZ=Asia/Shanghai
    command: sh -c "pip install flask flask-cors -i https://pypi.tuna.tsinghua.edu.cn/simple && python app.py"
    restart: always